version: '3.8'
services:
  nest-api:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    env_file:
      - .env

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - '3306:3306'
    env_file:
      - .env
    volumes:
      - mysql:/var/lib/mysql 

volumes:
  mysql:
    name: nest-db